config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get '/beauty_loop', to: 'pages#beauty_loop'
  get '/holding_page', to: 'pages#holding_page'
  get "/send_email", to: 'pages#send_email'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home, :beauty_loop, :holding_page, :send_email]

  def home
  end

  def beauty_loop
  end

  def holding_page
  end

  def send_email
    # message = params[:send_email]
    # ContactMailer.send_email_to_contact(message).deliver_now
    # redirect_to storages_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>TODO</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%#= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/beauty_loop.html.erb
<div class="container">
  <h1 class="text-center" style="margin: 50px 0;">BEAUTY LOOP</h1>
  <h2 class="text-center" style="margin: 50px 0;">Components</h2>
  <h3 style="margin: 20px 0;">Video Card</h3>

  <div style="display: flex;">
    <div class="insider-info-cards">
      <div class="insider-info-text">
        <p><strong>Ask the expert</strong></p>
        <p>Girlie talk with influencer Shantania Beckford</p>
      </div>
      <div class="insider-info-image" style="background-image: url('https://images.pexels.com/photos/457701/pexels-photo-457701.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260')"></div>
    </div>
    <div class="insider-info-cards">
      <div class="insider-info-text">
        <p><strong>Ask the expert</strong></p>
        <p>Girlie talk with influencer Shantania Beckford</p>
      </div>
      <div class="insider-info-image" style="background-image: url('https://images.pexels.com/photos/457701/pexels-photo-457701.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260')"></div>
    </div>
  </div>

</div>

app/views/pages/holding_page.html.erb
<div class="offers-banner">
  <p class="offers-banner-text">20% OFF YOUR FIRST ORDER</p>
</div>
<div class="logo-bar">
  <div class="logo-bar-section"></div>
  <div class="logo-bar-section middle-section">
    <%= image_tag 'beauty-loop.png' %>
  </div>
  <div class="logo-bar-section last-section">
    <p class="follow-us-instagram">Follow us: </p><i class="fab fa-instagram"></i>
  </div>
</div>
<div class="holding-page-image-banner" style="background-image: url('https://images.pexels.com/photos/457701/pexels-photo-457701.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260')"></div>
<div class="holding-page-text-banner">
  <div class="holding-page-text">
    <p>As women of colour we know filtering through the 100s of beauty brands to find the perfect product can be daunting</p>
    <p>Loop Beauty makes it easier and more effective. Partnering with your favourite beauty influencers we curate the very best beauty products for women of colour.</p>
    <p>Expert advice. Fun secrets. Master classes. Exciting stories. Perfect your look in one place.</p>
  </div>
</div>
<div class="holding-page-newsletter-banner">
  <h1 class="text-center" style="margin: 30px 0;">Sign Up Now</h1>
  <%= simple_form_for :send_email, url: send_email_path, method: :get do |f| %>
  <div class="form-inline">
    <div class="">
      <%= f.input :email, label: false, placeholder:'Email address' %>
    </div>
    <div class="">
      <%= f.button :button, type: :submit,  class: "contact-form-button" do %>
        <p>SEND</p>
      <% end %>
    </div>
  </div>
  <% end %>
  <p class="text-center">20% off your first order</p>
  <p class="text-center" style="color: #9E9E9E;">For press and business enquiries: hello@loopbeauty.co.uk</p>
</div>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "#", class: "navbar-brand" do %>
    <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", "#", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Messages", "#", class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>